Algoritmo "par ou impar condicional SE"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas Rafael
// Data atual  : 19/06/2021
Var
num: inteiro

Inicio
//entrada
escreval ("Digite um valor")

leia(num)
//processamento
se (num mod 2) =0 entao
  escreval("Este numero é par")
senao
  escreval("Este numero é impar")
fimse
//saida
Fimalgoritmo